### ISSUE TITLE
내용 수정 요청

### ISSUE THREAD

**Issue by laonmofu** [curioustorvald/roster-searcher-thingamajig#1]
안녕하세요! 일부 내용에 수정을 요청드리고자 이슈 남깁니다!
먼저 말씀드리기에 앞서, 저=소티=포키(최종 명의) 이며, 현재 트위터 계정 아이디는 @NekoSAIKYO 임을 알려드립니다.
태그된 트위터 계정 닉네임은 복희이나, 기존 활동시에는 여전히 포키를 사용했으므로 무시하셔도 됩니다.
ohiya님과의 관계는 동업자였으며, 이 수정사항 요청에 동의하였습니다.

**변경 요청**
1. Ohiya(찬물/차가운물)님은 현재는 작업을 그만 두셨으며, 찬물(개인)과 미니미 공방(브랜드), 두 트위터 계정이 모두 최근 삭제처리 되었습니다. 계정 자체가 존재하지 않으므로 따로 링크하실 필요 없습니다. (태그된 링크 삭제 요청)
2. 헤피는 양도 과정에서 이름이 미즈키/Mizuki 로 변경되었습니다. 디자인의 변경은 따로 없습니다.
3. 소티의 소유명의는 현재 포키이며, 바디 디자인의 변경이 있습니다. (원래 소지하고 있던 미니미 공방 제작의 소티 헤드와, 신님 제작의 호루라기의 바디 디자인이 합쳐졌습니다. 토끼와 잉어가 합쳐진 형태인지라 종족 변경이 필요할 것으로 예상됩니다.)
4. 리오르와 매화의 오너는 해외에 거주하고 계시며, 한국인이 아닌 외국인입니다. ??? 처리된 두 퍼슈트도 해외로 나갔을 가능성이 높습니다.

**삭제 요청(활동 중지)**
1. Cerulean(셀룰리안)은 더 이상 존재하지 않습니다.
2. 소티의 디자인 변경에서 소티가 호루라기의 디자인을 흡수했습니다.
위 두 사항은 오너님이 각별하게 요청하신 사항입니다. 활동 중지된 퍼슛이 검색에 포함되지 않아야 한다면 삭제 부탁드립니다.

긴 글 읽어주셔서 감사합니다! 이해하기 어려운 사항이 있으시거나, 추가로 요청하실 사항이 있으시다면 편하게 연락해 주세요.

**Comment by curioustorvald** [comment]
감사합니다 수정사항은 다음 업데이트 때 반영됩니당 :>
