### ISSUE TITLE
퍼슈트 검색체계에서, 제이(Jay)퍼슈트 색상에 대해 잘못된 정보가 있습니다.

### ISSUE THREAD

**Issue by jayshiin** [curioustorvald/roster-searcher-thingamajig#3]
**제이(Jay)의 색상 정보가 잘못되었습니다.**

색상 조합은 완전한 흰색이나, 베이지라고 적혀 있습니다.
눈은 청록색이나, 파란색이라고 적혀 있습니다.

**수정 요청 사항**

제이(Jay)의 색상 정보
색상 조합 **베이지 → 흰색**
눈 색깔 **파란색 → 청록색**

감사합니다.

**Comment by curioustorvald** [comment]
감사합니다 수정사항은 다음 업데이트 때 반영됩니당 :>
