### ISSUE TITLE
크로미움 기반 브라우저와 파이어폭스에서 이슈가 있습니다

### ISSUE THREAD

**Issue by potato03kth** [curioustorvald/roster-searcher-thingamajig#4]
플랫폼 : Windows 10 Home Version 21H2 
브라우저: Firefox Developer Edition 101.0 Beta 5 
---
플랫폼 : Window 11 Home Version 21H2 
브라우저: Firefox Version 100.0 
---
플랫폼 : Android 12
브라우저: Chrome 101.0.4951.61
---
플랫폼 : Window 11 Home Version 21H2
브라우저: Chrome 101.0.4951 
---
이슈 내용 : 퍼덱스 이하의 모든 도메인에서의 db 호출이 거부됩니다.
브라우저로부터 "**데이터베이스의 무결성 검증에 실패하였습니다: Undefined eye_colours '청색' for id 742**"라는 alert 받고, db는 호출되지 않습니다.
해당 이슈는 재생산이 가능하며, 해당 이슈가 발생한 모든 브라우저에서 이슈의 형태는 동일하였습니다.
위의 모든 플랫폼 - 브라우저 조합에서 이슈는 발생하였고, 오직 Window 10 Home Version 21H2 && Firefox Developer Edition 101.0 Beta 5 의 조합에서만 오류없이 문제없이 평소와 동일한 UX를 경험할 수 있었습니다.

**Comment by potato03kth** [comment]
또한 해당 이슈는  **WIndow 10 Home Version 21H2 && Microsoft Edge Version 101.0.1210.39** 에서도 동일하게 발생하였습니다

**Comment by curioustorvald** [comment]
12시 14시부로 해결되었습니다 감사합니다!
오류가 계속된다면 브라우저의 캐시를 비워주세요
